// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// `.env.local` y después `.env`, sin sobreescribir lo que ya esté en el entorno:
// el cargador es el mismo que usan los scripts de `scripts/`, y está aparte porque
// `dotenv/config` (que es lo que Prisma genera) solo mira `.env`.
// Ver el porqué en scripts/load-env.mjs.
import "./scripts/load-env.mjs";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
